version: '3'
services:
  app:
    image: devopsproject
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty15112003
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - devopscourseproject

  db:
    image: 'postgres:14-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty15112003
    networks:
      - devopscourseproject

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/main/resources/static:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - devopscourseproject

networks:
  devopscourseproject: